[book]
authors = ["otcova"]
language = "en"
multilingual = false
src = "src"
title = "Paperbit Documentation"

[build]
build-dir = "../docs"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
curly-quotes = true